### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by itsmo-ks** [eXtizi/SlamAutoDownload#1]
Heroku banned this repo because it violets their policy, any solution to deploy it ??

**Comment by eXtizi** [comment]
ysh! import the repo. , make it private. change the repo name.deploy

**Comment by itsmo-ks** [comment]
after 5min heroku ban my account.
can you add support for scalingo.com , it is like heroku

**Comment by itsmo-ks** [comment]
scalingo logs when i deployed the repo 
![Capture](https://user-images.githubusercontent.com/62901183/160240131-29539b1e-46ce-4a60-9053-e25ff7e4e693.PNG)

**Comment by itsmo-ks** [comment]
That's the full Logs https://anotepad.com/notes/7nxt9k5f

**Comment by eXtizi** [comment]
Sorry dont have time
